### ISSUE TITLE
Hadoop Error

### ISSUE THREAD

**Issue by TruongQToan** [phuonglh/ai.vitk.ner#1]
I've downloaded your tool to test on my machine. I'm so excited to test it but unfortunately, it got an error relate to hadoop. 
`WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 3
	at ai.vitk.ner.CorpusReader$$anonfun$readCoNLL$1$$anonfun$4.apply(CorpusReader.scala:30)
	at ai.vitk.ner.CorpusReader$$anonfun$readCoNLL$1$$anonfun$4.apply(CorpusReader.scala:28)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.mutable.ArrayOps$ofRef.map(ArrayOps.scala:186)
	at ai.vitk.ner.CorpusReader$$anonfun$readCoNLL$1.apply$mcVI$sp(CorpusReader.scala:28)
	at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:160)
	at ai.vitk.ner.CorpusReader$.readCoNLL(CorpusReader.scala:24)
	at ai.vitk.ner.Tagger$.combineNER(Tagger.scala:213)
	at ai.vitk.ner.Tagger$.main(Tagger.scala:244)
	at ai.vitk.ner.Tagger.main(Tagger.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:755)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:180)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:205)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:119)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
`
and I couldn't get the output. How should I install hadoop to avoid this error? Thank you very much.

**Comment by phuonglh** [comment]
Hello,

Can you tell me what command leads to this error? Are you training a model or running a pre-trained model?

Cheers,

**Comment by TruongQToan** [comment]
Thank you for your immediate reply. :)
I ran this command 
`./spark/bin/spark-submit target/ai.vitk.ner-1.0.jar --mode tag --input <input-file>`
I ran on a pre-trained model.
However, the command
`./spark/bin/spark-submit target/ai.vitk.ner-1.0.jar --mode eval`
executed normally, did not report any error.

**Comment by TruongQToan** [comment]
Here is my input file.

> ĐOÀN 1: (16 - 20 khách đi từ 28/7/2017 – 30/7/2017)
Ngày 1:  
7h – 7h15 Đón xe đi đến Hạ Long (Vui long cho điểm đón cụ thể)
11h30: Đến Hạ Long, lên tàu và nhận phòng. Sau đó ăn trưa trên tàu
Chiều thăm quan Vịnh Hạ Long, Hang Sửng sốt  (Tuỳ chuong trình của từng tàu khác nhau)
Ăn tối, sau đó tự do vui chơi trên tàu. Tham gia các chương trình trên tàu như  câu mực
Ngủ đêm trên tàu 4 sao - Flamingo Cruise hoặc tương đương
Ngày 2:
6h – 6h30 Sáng sẽ có hoạt động tập Tai Chi trên bong tàu
Ăn sáng, sau đó sẽ đi thăm đảo Titop và tắm biển
Ăn trưa  nhẹ sau đó khoảng 11.30 cập bến
Xe đưa đoàn  đến công viên Sun World vui chơi tự do (mọi chi phí khách tự trả) sau đó về khách sạn nhận phòng và tự do vui choi, tắm biển
Ngủ đêm tại khách sạn 4 sao (Halong Palace hoặc khách sạn tương đương)
Ngày 3:
Ăn sáng tại khách sạn
Nghỉ ngơi, tắm biển và mua sắm tự do
Buổi trưa trả phòng, ăn trưa  và lên đường về Hà Nội

**Comment by phuonglh** [comment]
Hello again,

Your input file is not well-formed in the format of NER. It should be in a column format, similar to the file 

src/main/resources/ner/vi/test.txt

By the way, to do NER, you should have a part-of-speech tagged tokens, not a plain text as your input.

Cheers,

**Comment by TruongQToan** [comment]
So to output  part-of-speech tagged tokens, can I use [Vitk -- Part-of-Speech Tagging](https://github.com/phuonglh/vn.vitk/blob/master/POS.md). Is this tool get plain text input.

**Comment by phuonglh** [comment]
Yes, that's right. However, you should convert the output of Vitk tokenizer and PoS tagger to the column format. And if chunking information is not provided, the resulting could be a bit less accurate.

**Comment by TruongQToan** [comment]
What is chunking information?

**Comment by phuonglh** [comment]
That's the third column of the test.txt file.

**Comment by TruongQToan** [comment]
OK. Thank you very much. I really appreciate your help.

**Comment by TruongQToan** [comment]
Apart from the POS tag column, do the input have to include the remaining column. Here is a part of my input file and it still isn't working.

>  	Ngày	N	 	 	 	 
1	M	 	 
7h	N	 	 
7h15	N	 	 
Đón	Np	 	 
xe	N	 	 
đi	V	 	 
đến	E	 	 
Hạ_Long	Np	 	 
Vui_long	V	 	 
cho	V	 	 
điểm	N	 	 
đón	V	 	 
cụ_thể	N	 	 
11h30	M	 	 
Đến	E	 	 
Hạ_Long	Np

**Comment by phuonglh** [comment]
Yes, it does need to include other columns. If you don't have info for those columns, make it a dummy content like a underscore. See the test file again for examples.
